### ISSUE TITLE
automatically unlock account

### ISSUE THREAD

**Issue by michielbdejong** [interledger-deprecated/ilp-plugin-ethereum#12]
Using https://github.com/ethereum/web3.js/blob/master/test/web3.personal.unlockAccount.js it should be possible to get rid of `authentication needed: password or unlock` errors

**Comment by sharafian** [comment]
the way you should do that is by just unlocking the account on your ethereum provider. You can pass the accounts you want to unlock as CLI parameters when you start it

**Comment by michielbdejong** [comment]
That's an option, yes, but that's an extra step, and if you forget to do that after each time you restart your geth node, it becomes quite annoying quite quickly.

I already implemented it in #13. Your option of unlocking via cli and then omitting `options.secret` will still work.
